name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main  # メインブランチにpushされたら実行

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - uses: actions/checkout@v3

      # Node.js をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 依存関係のインストール
      - name: Install dependencies
        run: npm ci

      # Viteでビルド
      - name: Build
        run: npm run build

      # GitHub Pagesにデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Viteのビルド成果物フォルダ
